### ISSUE TITLE
JSON file to download of bad terms and alternatives

### ISSUE THREAD

**Issue by nitrocode** [ietf/terminology#16] opened 2021-03-27 00:27 UTC
It would be nice to be able to download all this in a JSON block so we can do automated searches in code bases

e.g.

```json
{
  "whitelist": ["allowlist", "approved list", "pass list", "accept list", "permitted"],
  "blacklist": ["blocklist", "denylist", "unapproved list", "reject list", "refused", "prohibited"],
}
```

**Comment by larseggert** [comment] 2021-03-27 06:12
I think this is a duplicate of #4. Also, see #14.

**Closed** 2021-03-27 12:52 UTC
